name: Build and Deploy Windows Application

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Prepare Build Directory
      run: |
        # Clear the build directory
        if (Test-Path "build") {Remove-Item -Path "build" -Recurse -Force}

        # Create a new build directory
        New-Item -ItemType Directory -Path "build"

    - name: Prepare Godot Editor
      run: |
        # Download the Godot Editor
        if (-not (Test-Path "godot")) {
            New-Item -ItemType Directory -Path "godot"
            $client = new-object System.Net.WebClient
            $client.DownloadFile("https://github.com/GodotSteam/GodotSteam/releases/download/v4.7-mp/win64-g422-s159-gs47-mp.zip",".\godot\godot.zip")
            cd godot
            tar -xf godot.zip
            del godot.zip
            cd ..
        }

    - name: Build the Windows Application
      run: |
        # Build the Windows Application
        .\godot\godotsteam.multiplayer.422.editor.windows.64.exe --headless --path . --export-release 'Windows Desktop' .\build\godotsteamtest.exe
        ls build

    - name: Copy the Steam API
      run: |
        # Copy the Steam API
        Copy-Item -Path ".\godot\steam_api64.dll" -Destination ".\build\"

    - name: Push to Releases Of Radiance Repository
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        EMAIL: ${{ secrets.EMAIL }}
      run: |
        # Initialise a new repository.
        cd build
        git init
        git config --global user.name "Rohan Fredriksson"
        git config --global user.email $EMAIL
        git config --global pull.rebase false
        git add .
        git commit -m "Release"
        git branch -M master
        git remote add origin https://${{ secrets.TOKEN }}@github.com/RohanFredriksson/ReleasesOfRadiance.git
        git push -uf origin master
